name: 🚀 Deploy website

on:
  workflow_run:
    workflows:
      - 'CI'
    branches:
      - master
    types: [completed]
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_website
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Export static website to staging
        run: |
          yarn install --frozen-lockfile
          cp .env.staging .env.production
          yarn build
          yarn export

      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan webapps.flathub.org >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          rsync -rP --delete out/ deploy@webapps.flathub.org:
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
